name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # ajuste conforme sua versão

      - name: Restaurar dependências
        run: dotnet restore Rubik.sln

      - name: Compilar solução
        run: dotnet build Rubik.sln --configuration Release --no-restore

      - name: Executar testes
        run: dotnet test Rubik.Tests/Rubik.Tests.csproj --configuration Release --no-build --verbosity normal

      - name: Publicar artefato (WPF)
        if: success()
        run: dotnet publish Rubik.WPF/Rubik.WPF.csproj -c Release -o ./artifacts/WPF

      - name: Salvar artefatos de build
        uses: actions/upload-artifact@v4
        with:
          name: rubik-build
          path: ./artifacts/WPF

